#!/usr/bin/env ruby
require 'yaml'
ca = File.read('director_ca')
private_key = File.read('director_ca_private_key')
openstack_ca_cert = File.read('bosh_openstack_ca_cert')

creds = {
   'openstack_ca_cert' => openstack_ca_cert.empty? ? '~' : openstack_ca_cert,
   'default_ca' => {
      'ca' => ca,
      'certificate' => ca,
      'private_key' => private_key
   }
}.to_yaml

puts creds