---
- project:
    check:
      jobs:
        - bosh-openstack-cpi-release-acceptance-test
        - bosh-openstack-cpi-release-acceptance-test-queens
        - bosh-openstack-cpi-release-acceptance-test-pike
        - bosh-openstack-cpi-release-acceptance-test-ocata
        - bosh-openstack-cpi-release-acceptance-test-newton
    periodic:
      jobs:
        - bosh-openstack-cpi-release-acceptance-test:
            branches: master
        - bosh-openstack-cpi-release-acceptance-test-queens:
            branches: master
        - bosh-openstack-cpi-release-acceptance-test-pike:
            branches: master
        - bosh-openstack-cpi-release-acceptance-test-ocata:
            branches: master
        - bosh-openstack-cpi-release-acceptance-test-newton:
            branches: master

- job:
    name: bosh-openstack-cpi-release-acceptance-test
    parent: init-test
    description: |
      This job validation tests of bosh-openstack-cpi-release aganist OpenStack master branch
    run: .zuul/playbooks/bosh-openstack-cpi-release-acceptance-test/run.yaml

- job:
    name: bosh-openstack-cpi-release-acceptance-test-queens
    parent: bosh-openstack-cpi-release-acceptance-test
    description: |
      This job validation tests of bosh-openstack-cpi-release aganist OpenStack Queens release
    vars:
      global_env:
        OS_BRANCH: stable/queens

- job:
    name: bosh-openstack-cpi-release-acceptance-test-pike
    parent: bosh-openstack-cpi-release-acceptance-test
    description: |
      This job validation tests of bosh-openstack-cpi-release aganist OpenStack Pike release
    vars:
      global_env:
        OS_BRANCH: stable/pike

- job:
    name: bosh-openstack-cpi-release-acceptance-test-ocata
    parent: bosh-openstack-cpi-release-acceptance-test
    description: |
      This job validation tests of bosh-openstack-cpi-release aganist OpenStack Ocata release
    vars:
      global_env:
        OS_BRANCH: stable/ocata

- job:
    name: bosh-openstack-cpi-release-acceptance-test-newton
    parent: bosh-openstack-cpi-release-acceptance-test
    description: |
      This job validation tests of bosh-openstack-cpi-release aganist OpenStack Newton release
    vars:
      global_env:
        OS_BRANCH: stable/newton
