---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/bosh-openstack-cpi-release/openstack-cpi-release
    username: ((github_read_write_packages.username))
    password: ((github_read_write_packages.password))
inputs:
  - name: bosh-openstack-cpi-release
  - name: terraform-cpi
  - name: bosh-deployment
outputs:
  - name: bosh-director-deployment
run:
  path: bosh-openstack-cpi-release/ci/tasks/deploy-manual-networking.sh
params:
  openstack_flavor:                    ""
  openstack_connection_timeout:        ""
  openstack_read_timeout:              ""
  openstack_write_timeout:             ""
  openstack_state_timeout:             ""
  openstack_auth_url:                  ""
  openstack_username:                  ""
  openstack_api_key:                   ""
  openstack_domain:                    ""
  DEBUG_BATS:                          ""
  openstack_file_path:                 ""
  availability_zone:                   replace-me
  USE_GOLANG_CPI:                      "true"
