---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/bosh-openstack-cpi-release/openstack-cpi-release
    username: ((github_read_write_packages.username))
    password: ((github_read_write_packages.password))
inputs:
  - name: bosh-openstack-cpi-release
  - name: lifecycle-log
outputs:
  - name: publish
run:
  path: bosh-openstack-cpi-release/ci/tasks/publish-api-calls.sh
params:
  publish_api_calls_enabled:  replace-me
