---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/bosh-openstack-cpi-release/openstack-cpi-release
    username: ((github_read_write_packages.username))
    password: ((github_read_write_packages.password))
inputs:
  - name: bosh-openstack-cpi-release
  - name: stemcell
  - name: bats
  - name: terraform-cpi
  - name: bosh-director-deployment
run:
  path: bosh-openstack-cpi-release/ci/tasks/run-manual-networking-bats.sh
params:
  stemcell_name:                            replace-me
  openstack_flavor_with_ephemeral_disk:     replace-me
  openstack_flavor_with_no_ephemeral_disk:  replace-me
  availability_zone:                        replace-me
  bats_rspec_tags:                          ""
