#!/usr/bin/env bash

set -e

source bosh-cpi-release/ci/tasks/utils.sh

ensure_not_replace_value BOSH_OPENSTACK_AUTH_URL
ensure_not_replace_value BOSH_OPENSTACK_USERNAME
ensure_not_replace_value BOSH_OPENSTACK_API_KEY
ensure_not_replace_value BOSH_OPENSTACK_TENANT
ensure_not_replace_value BOSH_OPENSTACK_MANUAL_IP
ensure_not_replace_value BOSH_OPENSTACK_NET_ID
ensure_not_replace_value BOSH_OPENSTACK_STEMCELL_ID
ensure_not_replace_value BOSH_OPENSTACK_DEFAULT_KEY_NAME
ensure_not_replace_value BOSH_CLI_SILENCE_SLOW_LOAD_WARNING
ensure_not_replace_value BOSH_OPENSTACK_VOLUME_TYPE
ensure_not_replace_value BOSH_OPENSTACK_CONNECT_TIMEOUT
ensure_not_replace_value BOSH_OPENSTACK_READ_TIMEOUT
ensure_not_replace_value BOSH_OPENSTACK_WRITE_TIMEOUT

source /etc/profile.d/chruby-with-ruby-2.1.2.sh

cd bosh-cpi-release/src/bosh_openstack_cpi

bundle install
bundle exec rspec spec/integration
