source 'https://rubygems.org'

gem 'bosh_common'
gem 'bosh_cpi'
gem 'excon'
gem 'fog-openstack'
gem 'httpclient'
gem 'membrane'
gem 'netaddr'

group :development, :test do
  gem 'minitar'
  gem 'pry-byebug'
  gem 'rb-readline'
  gem 'rake'
  gem 'rspec'
  gem 'rspec-its'
  gem 'rubocop'
  gem 'rubocop-git'
  gem 'timecop'
  gem 'webmock'
  gem 'bosh-template'
end
