source 'https://rubygems.org'

gem 'bosh_common'
gem 'bosh_cpi',      '=2.3.0'
gem 'excon',         '~>0.49'
gem 'fog-openstack', '~>0.1.24'
gem 'httpclient',    '=2.8.3'
gem 'membrane',      '~>1.1.0'
gem 'netaddr',       '~>1.5.0'

group :development, :test do
  gem 'minitar', '~> 0.5.4'
  gem 'rake', '~>10.3.2'
  gem 'rspec', '~> 3.3.0'
  gem 'rspec-its', '~> 1.0.1'
  gem 'timecop', '~>0.7.1'
  gem 'webmock', '~>2.3.2'
end
