#!/usr/bin/env bash

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

"${script_dir}/install-git-hooks"

pushd "${script_dir}/../src/bosh_openstack_cpi"
  bundle install
  bundle exec rspec "spec/unit"
popd
