#!/bin/bash

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

"${script_dir}/install-git-hooks"

pushd "${script_dir}/../src/bosh_openstack_cpi"
  source "${script_dir}/check-ruby-version"

  bundle install
  bundle exec rspec "spec/unit/bosh_release"
popd
