// Code generated by counterfeiter. DO NOT EDIT.
package imagefakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/config"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/image"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/properties"
)

type FakeImageService struct {
	CreateImageStub        func(properties.CreateStemcell, config.OpenstackConfig) (string, error)
	createImageMutex       sync.RWMutex
	createImageArgsForCall []struct {
		arg1 properties.CreateStemcell
		arg2 config.OpenstackConfig
	}
	createImageReturns struct {
		result1 string
		result2 error
	}
	createImageReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	DeleteImageStub        func(string) error
	deleteImageMutex       sync.RWMutex
	deleteImageArgsForCall []struct {
		arg1 string
	}
	deleteImageReturns struct {
		result1 error
	}
	deleteImageReturnsOnCall map[int]struct {
		result1 error
	}
	GetImageStub        func(string) (string, error)
	getImageMutex       sync.RWMutex
	getImageArgsForCall []struct {
		arg1 string
	}
	getImageReturns struct {
		result1 string
		result2 error
	}
	getImageReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	UploadImageStub        func(string, string) error
	uploadImageMutex       sync.RWMutex
	uploadImageArgsForCall []struct {
		arg1 string
		arg2 string
	}
	uploadImageReturns struct {
		result1 error
	}
	uploadImageReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeImageService) CreateImage(arg1 properties.CreateStemcell, arg2 config.OpenstackConfig) (string, error) {
	fake.createImageMutex.Lock()
	ret, specificReturn := fake.createImageReturnsOnCall[len(fake.createImageArgsForCall)]
	fake.createImageArgsForCall = append(fake.createImageArgsForCall, struct {
		arg1 properties.CreateStemcell
		arg2 config.OpenstackConfig
	}{arg1, arg2})
	stub := fake.CreateImageStub
	fakeReturns := fake.createImageReturns
	fake.recordInvocation("CreateImage", []interface{}{arg1, arg2})
	fake.createImageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImageService) CreateImageCallCount() int {
	fake.createImageMutex.RLock()
	defer fake.createImageMutex.RUnlock()
	return len(fake.createImageArgsForCall)
}

func (fake *FakeImageService) CreateImageCalls(stub func(properties.CreateStemcell, config.OpenstackConfig) (string, error)) {
	fake.createImageMutex.Lock()
	defer fake.createImageMutex.Unlock()
	fake.CreateImageStub = stub
}

func (fake *FakeImageService) CreateImageArgsForCall(i int) (properties.CreateStemcell, config.OpenstackConfig) {
	fake.createImageMutex.RLock()
	defer fake.createImageMutex.RUnlock()
	argsForCall := fake.createImageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeImageService) CreateImageReturns(result1 string, result2 error) {
	fake.createImageMutex.Lock()
	defer fake.createImageMutex.Unlock()
	fake.CreateImageStub = nil
	fake.createImageReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImageService) CreateImageReturnsOnCall(i int, result1 string, result2 error) {
	fake.createImageMutex.Lock()
	defer fake.createImageMutex.Unlock()
	fake.CreateImageStub = nil
	if fake.createImageReturnsOnCall == nil {
		fake.createImageReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.createImageReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImageService) DeleteImage(arg1 string) error {
	fake.deleteImageMutex.Lock()
	ret, specificReturn := fake.deleteImageReturnsOnCall[len(fake.deleteImageArgsForCall)]
	fake.deleteImageArgsForCall = append(fake.deleteImageArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeleteImageStub
	fakeReturns := fake.deleteImageReturns
	fake.recordInvocation("DeleteImage", []interface{}{arg1})
	fake.deleteImageMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImageService) DeleteImageCallCount() int {
	fake.deleteImageMutex.RLock()
	defer fake.deleteImageMutex.RUnlock()
	return len(fake.deleteImageArgsForCall)
}

func (fake *FakeImageService) DeleteImageCalls(stub func(string) error) {
	fake.deleteImageMutex.Lock()
	defer fake.deleteImageMutex.Unlock()
	fake.DeleteImageStub = stub
}

func (fake *FakeImageService) DeleteImageArgsForCall(i int) string {
	fake.deleteImageMutex.RLock()
	defer fake.deleteImageMutex.RUnlock()
	argsForCall := fake.deleteImageArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeImageService) DeleteImageReturns(result1 error) {
	fake.deleteImageMutex.Lock()
	defer fake.deleteImageMutex.Unlock()
	fake.DeleteImageStub = nil
	fake.deleteImageReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImageService) DeleteImageReturnsOnCall(i int, result1 error) {
	fake.deleteImageMutex.Lock()
	defer fake.deleteImageMutex.Unlock()
	fake.DeleteImageStub = nil
	if fake.deleteImageReturnsOnCall == nil {
		fake.deleteImageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteImageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImageService) GetImage(arg1 string) (string, error) {
	fake.getImageMutex.Lock()
	ret, specificReturn := fake.getImageReturnsOnCall[len(fake.getImageArgsForCall)]
	fake.getImageArgsForCall = append(fake.getImageArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetImageStub
	fakeReturns := fake.getImageReturns
	fake.recordInvocation("GetImage", []interface{}{arg1})
	fake.getImageMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImageService) GetImageCallCount() int {
	fake.getImageMutex.RLock()
	defer fake.getImageMutex.RUnlock()
	return len(fake.getImageArgsForCall)
}

func (fake *FakeImageService) GetImageCalls(stub func(string) (string, error)) {
	fake.getImageMutex.Lock()
	defer fake.getImageMutex.Unlock()
	fake.GetImageStub = stub
}

func (fake *FakeImageService) GetImageArgsForCall(i int) string {
	fake.getImageMutex.RLock()
	defer fake.getImageMutex.RUnlock()
	argsForCall := fake.getImageArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeImageService) GetImageReturns(result1 string, result2 error) {
	fake.getImageMutex.Lock()
	defer fake.getImageMutex.Unlock()
	fake.GetImageStub = nil
	fake.getImageReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImageService) GetImageReturnsOnCall(i int, result1 string, result2 error) {
	fake.getImageMutex.Lock()
	defer fake.getImageMutex.Unlock()
	fake.GetImageStub = nil
	if fake.getImageReturnsOnCall == nil {
		fake.getImageReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getImageReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeImageService) UploadImage(arg1 string, arg2 string) error {
	fake.uploadImageMutex.Lock()
	ret, specificReturn := fake.uploadImageReturnsOnCall[len(fake.uploadImageArgsForCall)]
	fake.uploadImageArgsForCall = append(fake.uploadImageArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.UploadImageStub
	fakeReturns := fake.uploadImageReturns
	fake.recordInvocation("UploadImage", []interface{}{arg1, arg2})
	fake.uploadImageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImageService) UploadImageCallCount() int {
	fake.uploadImageMutex.RLock()
	defer fake.uploadImageMutex.RUnlock()
	return len(fake.uploadImageArgsForCall)
}

func (fake *FakeImageService) UploadImageCalls(stub func(string, string) error) {
	fake.uploadImageMutex.Lock()
	defer fake.uploadImageMutex.Unlock()
	fake.UploadImageStub = stub
}

func (fake *FakeImageService) UploadImageArgsForCall(i int) (string, string) {
	fake.uploadImageMutex.RLock()
	defer fake.uploadImageMutex.RUnlock()
	argsForCall := fake.uploadImageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeImageService) UploadImageReturns(result1 error) {
	fake.uploadImageMutex.Lock()
	defer fake.uploadImageMutex.Unlock()
	fake.UploadImageStub = nil
	fake.uploadImageReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImageService) UploadImageReturnsOnCall(i int, result1 error) {
	fake.uploadImageMutex.Lock()
	defer fake.uploadImageMutex.Unlock()
	fake.UploadImageStub = nil
	if fake.uploadImageReturnsOnCall == nil {
		fake.uploadImageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.uploadImageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImageService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createImageMutex.RLock()
	defer fake.createImageMutex.RUnlock()
	fake.deleteImageMutex.RLock()
	defer fake.deleteImageMutex.RUnlock()
	fake.getImageMutex.RLock()
	defer fake.getImageMutex.RUnlock()
	fake.uploadImageMutex.RLock()
	defer fake.uploadImageMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeImageService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ image.ImageService = new(FakeImageService)
