---
custom:
  timeouts:
    long: &timeouts-long 3h
  debug_bats: &debug_bats true

jobs:
- name: create-openstack-cpi-release-docker-image
  serial: true
  plan:
  - get: bosh-openstack-cpi-release
  - put: openstack-cpi-release-docker-image
    params:
      build: "bosh-openstack-cpi-release/ci/docker/openstack-cpi-release"

- name: pipeline-locator
  plan:
  - get: bosh-openstack-cpi-release
  - task: pipeline-location
    file: bosh-openstack-cpi-release/ci/tasks/pipeline-locator.yml
    params: { PIPELINE_FILENAME: "pipeline.yml" }
    input_mapping: { pipeline-repo: bosh-openstack-cpi-release }

- name: run-specs
  serial: true
  plan:
  - in_parallel:
    - get: openstack-cpi-release-docker-image
    - get: bosh-openstack-cpi-release
      timeout: *timeouts-long
      trigger: true
  - task: run-unit-specs
    file: bosh-openstack-cpi-release/ci/tasks/run-unit-specs.yml
    image: openstack-cpi-release-docker-image

- name: lifecycle
  serial: true
  serial_groups: [ cleanup-lock-lifecycle ]
  plan:
  - in_parallel:
    - get: bosh-openstack-cpi-release
      passed: [ run-specs ]
      timeout: *timeouts-long
      trigger: true
    - get: openstack-lifecycle-stemcell
      resource: openstack-ubuntu-jammy-stemcell
      timeout: *timeouts-long

  - task: write_ca_file
    tags: [ "openstack" ]
    file: bosh-openstack-cpi-release/ci/tasks/write-ca-file.yml
    image: openstack-cpi-release-docker-image
    params:
      file_content: ((concourse_openstack_auth.openstack_ca_cert))

  - put: terraform-cpi
    tags: [ "openstack" ]
    timeout: *timeouts-long
    params:
      env_name: "lifecycle-openstack-tests"
      terraform_source: bosh-openstack-cpi-release/ci/terraform/ci/lifecycle
      vars: &lifecycle-terraform-vars
        prefix: "lifecycle-openstack-tests"
        auth_url: ((concourse_openstack_auth.auth_url))
        cacert_file: ((config-json.tf_ca_file_path))
        user_name: ((config-json.openstack_username))
        password: ((config-json.openstack_password))
        domain_name: ((config-json.lifecycle_openstack_domain))
        project_name: ((config-json.openstack_project))
        ext_net_id: ((config-json.tf_external_network_id))
        ext_net_name: ((config-json.tf_external_network_name))
        region_name: ((config-json.tf_region_name))
        openstack_default_key_public_key: ((config-json.tf_default_public_key))
        dns_nameservers: ((config-json.tf_dns_nameservers))
        use_lbaas: false
  - do:
    - task: test
      tags: [ "openstack" ]
      timeout: *timeouts-long
      file: bosh-openstack-cpi-release/ci/tasks/run-lifecycle.yml
      image: openstack-cpi-release-docker-image
      params:
        BOSH_OPENSTACK_DOMAIN: ((config-json.lifecycle_openstack_domain))
        BOSH_OPENSTACK_PROJECT: ((config-json.openstack_project))
        BOSH_OPENSTACK_USERNAME_V2: ((config-json.openstack_username))
        BOSH_OPENSTACK_AUTH_URL_V3: ((concourse_openstack_auth.auth_url))
        BOSH_OPENSTACK_USERNAME_V3: ((config-json.openstack_username))
        BOSH_OPENSTACK_API_KEY_V3: ((config-json.openstack_password))
        BOSH_CLI_SILENCE_SLOW_LOAD_WARNING: true
        BOSH_OPENSTACK_VOLUME_TYPE: ((config-json.lifecycle_openstack_volume_type))
        BOSH_OPENSTACK_CONNECT_TIMEOUT: "600"
        BOSH_OPENSTACK_READ_TIMEOUT: "120"
        BOSH_OPENSTACK_WRITE_TIMEOUT: "120"
        BOSH_OPENSTACK_CA_CERT: ((concourse_openstack_auth.openstack_ca_cert))
        BOSH_OPENSTACK_FLAVOR_WITH_NO_ROOT_DISK: ((config-json.openstack_flavor_with_no_root_disk))
        BOSH_OPENSTACK_AVAILABILITY_ZONE: ((config-json.availability_zone))
        BOSH_OPENSTACK_EXCLUDE_CINDER_V1: true
    - put: lifecycle-log
      tags: [ "openstack" ]
      timeout: *timeouts-long
      params: { file: output/lifecycle.log }
    ensure:
      put: terraform-cpi
      tags: [ "openstack" ]
      params:
        action: destroy
        env_name: "lifecycle-openstack-tests"
        terraform_source: bosh-openstack-cpi-release/ci/terraform/ci/lifecycle
        vars: *lifecycle-terraform-vars
      get_params:
        action: destroy

- name: bats-ubuntu-manual
  serial: true
  serial_groups: [ cleanup-lock-bats-ubuntu-manual ]
  plan:
  - in_parallel:
    - { trigger: true, passed: [ run-specs ], get: bosh-openstack-cpi-release, timeout: *timeouts-long }
    - { trigger: false,                    get: bosh-release, timeout: *timeouts-long }
    - { trigger: true,                    get: stemcell-director, resource: openstack-ubuntu-jammy-stemcell, timeout: *timeouts-long }
    - { trigger: false,                    get: stemcell, resource: openstack-ubuntu-jammy-stemcell, timeout: *timeouts-long }
    - { trigger: false,                    get: bats, timeout: *timeouts-long }
    - { trigger: false,                    get: bosh-deployment, timeout: *timeouts-long }

  - put: terraform-cpi
    tags: [ "openstack" ]
    timeout: *timeouts-long
    params:
      env_name: bats-ubuntu-manual
      terraform_source: bosh-openstack-cpi-release/ci/terraform/ci/bats-manual
      vars: &bats-terraform-vars
        prefix: "bats-ubuntu-manual"
        auth_url: ((concourse_openstack_auth.auth_url))
        domain_name: ((concourse_openstack_auth.openstack_domain))
        user_name: ((config-json.openstack_username))
        password: ((config-json.openstack_password))
        project_name: ((config-json.openstack_project))
        cacert_file: ((config-json.tf_ca_file_path))
        region_name: ((config-json.tf_region_name))
        primary_net_name: "bats-ubuntu-manual-primary"
        primary_net_cidr: "10.0.4.0/24"
        primary_net_allocation_pool_start: "10.0.4.200"
        primary_net_allocation_pool_end: "10.0.4.254"
        secondary_net_name: "bats-ubuntu-manual-secondary"
        secondary_net_cidr: "10.0.5.0/24"
        secondary_net_allocation_pool_start: "10.0.5.200"
        secondary_net_allocation_pool_end: "10.0.5.254"
        ext_net_name: ((config-json.tf_external_network_name))
        ext_net_id: ((config-json.tf_external_network_id))
        ext_net_cidr: ((config-json.tf_ext_net_cidr))
        dns_nameservers: ((config-json.tf_dns_nameservers))
        concourse_external_network_cidr: null
        openstack_default_key_public_key: ((config-json.tf_default_public_key))

  - do:
    - task: deploy
      tags: [ "openstack" ]
      timeout: *timeouts-long
      file: bosh-openstack-cpi-release/ci/tasks/deploy-manual-networking.yml
      params:
        openstack_flavor: "m1.small"
        openstack_connection_timeout: "600"
        openstack_read_timeout: "180"
        openstack_write_timeout: "180"
        openstack_state_timeout: "900"
        openstack_auth_url: ((concourse_openstack_auth.auth_url))
        openstack_username: ((config-json.openstack_username))
        openstack_api_key: ((config-json.openstack_password))
        openstack_domain: ((concourse_openstack_auth.openstack_domain))
        distro: "ubuntu"
        availability_zone: ((config-json.availability_zone))
        #NOTE: The CA cert path here is currently relative to the 'bosh-director-deployment' directory.
        openstack_ca_file_path: ((concourse_openstack_auth.openstack_ca_cert_path))
        DEBUG_BATS: *debug_bats

    - task: test
      tags: [ "openstack" ]
      timeout: *timeouts-long
      file: bosh-openstack-cpi-release/ci/tasks/run-manual-networking-bats.yml
      params:
        stemcell_name: "bosh-openstack-kvm-ubuntu-jammy-go_agent"
        openstack_flavor_with_ephemeral_disk: ((config-json.openstack_flavor_with_ephemeral_disk))
        openstack_flavor_with_no_ephemeral_disk: ((config-json.openstack_flavor_with_no_ephemeral_disk))
        availability_zone: ((config-json.availability_zone))
        DEBUG_BATS: *debug_bats
        bats_rspec_tags: "--tag ~ssh"
      ensure:
        task: print-task-errors
        tags: [ "openstack" ]
        timeout: *timeouts-long
        file: bosh-openstack-cpi-release/ci/tasks/print_task_errors.yml
    ensure:
      do:
      - task: teardown-director
        tags: [ "openstack" ]
        timeout: *timeouts-long
        file: bosh-openstack-cpi-release/ci/tasks/teardown-director.yml
        ensure:
          put: terraform-cpi
          tags: [ "openstack" ]
          params:
            action: destroy
            env_name: bats-ubuntu-manual
            terraform_source: bosh-openstack-cpi-release/ci/terraform/ci/bats-manual
            vars: *bats-terraform-vars
          get_params:
            action: destroy

- name: bump-major
  serial_groups: [ version ]
  plan:
    - put: release-version-semver
      params:
        bump: major

- name: bump-minor
  serial_groups: [ version ]
  plan:
    - put: release-version-semver
      params:
        bump: minor

- name: bump-patch
  serial_groups: [ version ]
  plan:
    - put: release-version-semver
      params:
        bump: patch

- name: automatically-release-new-patch
  serial_groups: [ version ]
  plan:
    - in_parallel:
        - get: bosh-openstack-cpi-release
          trigger: true
          passed:
            - lifecycle
            - bats-ubuntu-manual
        - get: bosh-shared-ci
        - get: version
          resource: release-version-semver
        - get: patched-version
          resource: release-version-semver
          params:
            bump: patch
        - get: bosh-security-scanner-registry-image
    - try:
        task: check-for-patched-cves
        file: bosh-shared-ci/tasks/release/check-for-patched-cves.yml
        image: bosh-security-scanner-registry-image
        input_mapping:
          input_repo: bosh-openstack-cpi-release
        params:
          GIT_PRIVATE_KEY: ((github_deploy_key_bosh-openstack-cpi-release.private_key))
          SEVERITY: CRITICAL,HIGH
        on_success:
          do:
            - put: release-notes
              params:
                file: release-notes/release-notes.md
            - put: release-version-semver
              params:
                file: patched-version/version
    - task: ensure-cve-checker-succeeded
      file: bosh-shared-ci/tasks/release/ensure-task-succeeded.yml
      image: bosh-security-scanner-registry-image
      input_mapping:
        task-output-folder: patched_cves
    - try:
        task: check-for-updated-vendored-packages
        file: bosh-shared-ci/tasks/release/check-for-updated-vendored-packages.yml
        image: bosh-security-scanner-registry-image
        input_mapping:
          input_repo: bosh-openstack-cpi-release
        params:
          PACKAGES:
            - golang-1-linux
            - openstack-ruby-3.1
        on_success:
          do:
            - put: release-notes
              params:
                file: release-notes/release-notes.md
            - put: release-version-semver
              params:
                file: patched-version/version
    - task: ensure-vendored-package-checker-succeeded
      file: bosh-shared-ci/tasks/release/ensure-task-succeeded.yml
      image: bosh-security-scanner-registry-image
      input_mapping:
        task-output-folder: package-updates

- name: promote-candidate
  disable_manual_trigger: true
  serial_groups: [ version ]
  plan:
  - in_parallel:
    - get: bosh-shared-ci
    - get: bosh-openstack-cpi-release
      passed:
      - lifecycle
      - bats-ubuntu-manual
    - get: version
      resource: release-version-semver
      trigger: true
    - get: release-notes
  - task: promote
    tags: [ "openstack" ]
    timeout: *timeouts-long
    file: bosh-shared-ci/tasks/release/create-final-release.yml
    input_mapping:
      release_repo: bosh-openstack-cpi-release
    params:
      GIT_USER_NAME: CI Bot
      GIT_USER_EMAIL: bots@cloudfoundry.org
      PRIVATE_YML: |
        blobstore:
          provider: gcs
          options:
            credentials_source: static
            json_key: '((cloud-foundry-gcp-credentials))'
  - put: bosh-openstack-cpi-release
    timeout: *timeouts-long
    params:
      repository: release_repo
      rebase: true
      tag: release_metadata/tag-name
  - put: bosh-openstack-cpi-release-github-release
    params:
      name: release_metadata/tag-name
      tag: release_metadata/tag-name
      body: release-notes/release-notes
      commitish: bosh-openstack-cpi-release/.git/ref
      generate_release_notes: true
  - put: release-notes
    params:
      file: release_metadata/empty-file

- name: bump-deps
  plan:
  - in_parallel:
    - get: bosh-openstack-cpi-release
    - get: ruby-release
    - get: bosh-ruby-release-registry-image
    - get: openstack-cpi-release-docker-image
    - get: weekly
      trigger: true
  - task: bump-gems
    image: bosh-ruby-release-registry-image
    file: ruby-release/ci/tasks/shared/bump-gems.yml
    input_mapping:
      input-repo: bosh-openstack-cpi-release
    output_mapping:
      output-repo: bosh-openstack-cpi-release
    params:
      GEM_DIRS: src/bosh_openstack_cpi
      GIT_USER_NAME: CI Bot
      GIT_USER_EMAIL: bots@cloudfoundry.org
      PACKAGE: ruby-3.1
      VENDOR: true
  - task: run-unit-specs
    file: bosh-openstack-cpi-release/ci/tasks/run-unit-specs.yml
    image: openstack-cpi-release-docker-image
  - put: bosh-openstack-cpi-release
    params:
      repository: bosh-openstack-cpi-release
      rebase: true

- name: bump-bosh-packages
  plan:
  - in_parallel:
    - get: bosh-openstack-cpi-release
    - get: ruby-release
      trigger: true
    - get: golang-release
      trigger: true
    - get: bosh-ecosystem-concourse-image
    - get: openstack-cpi-release-docker-image
  - task: bump-golang-packages
    file: golang-release/ci/tasks/shared/bump-golang-package.yml
    input_mapping:
      input_repo: bosh-openstack-cpi-release
    output_mapping:
      output_repo: bosh-openstack-cpi-release
    params:
      PACKAGES: [ golang-1-linux ]
      PRIVATE_YML: |
        blobstore:
          provider: gcs
          options:
            credentials_source: static
            json_key: '((cloud-foundry-gcp-credentials))'
  - task: bump-ruby-package
    image: bosh-ecosystem-concourse-image
    file: ruby-release/ci/tasks/shared/bump-ruby-package.yml
    input_mapping:
      bosh-release: bosh-openstack-cpi-release
    output_mapping:
      bosh-release: bosh-openstack-cpi-release
    params:
      GIT_USER_NAME: CI Bot
      GIT_USER_EMAIL: cf-bosh-eng@pivotal.io
      PACKAGE: ruby-3.1
      PACKAGE_PREFIX: "openstack"
      PRIVATE_YML: |
        blobstore:
          provider: gcs
          options:
            credentials_source: static
            json_key: '((cloud-foundry-gcp-credentials))'
      RUBY_VERSION_PATH: src/bosh_openstack_cpi/.ruby-version
  - task: run-unit-specs
    file: bosh-openstack-cpi-release/ci/tasks/run-unit-specs.yml
    image: openstack-cpi-release-docker-image
  - put: bosh-openstack-cpi-release
    params:
      repository: bosh-openstack-cpi-release
      rebase: true

resource_types:
- name: terraform
  type: registry-image
  check_every: 168h
  source:
    repository: ljfranklin/terraform-resource
    username: ((docker.username))
    password: ((docker.password))
- name: bosh-release
  type: registry-image
  check_every: 168h
  source:
    repository: dpb587/bosh-release-resource
    username: ((docker.username))
    password: ((docker.password))
- name: gcs
  type: registry-image
  check_every: 168h
  source:
    repository: frodenas/gcs-resource
    username: ((docker.username))
    password: ((docker.password))
- name: semver
  type: registry-image
  check_every: 168h
  source:
    repository: concourse/semver-resource
    username: ((docker.username))
    password: ((docker.password))

resources:
- name: bosh-shared-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-shared-ci.git
    private_key: ((github_deploy_key_bosh-shared-ci.private_key))

- name: terraform-cpi
  type: terraform
  tags: [ "openstack" ]
  source:
    backend_type: gcs
    backend_config:
      bucket: bosh-openstack-cpi-blobs
      prefix: terraform
      credentials: ((cloud-foundry-gcp-credentials))
    vars:
      region: us-east-1
      access_key: ((bosh-openstack-cpi-ci_assume_aws_access_key.username))
      secret_key: ((bosh-openstack-cpi-ci_assume_aws_access_key.password))
      role_arn: ((bosh-openstack-cpi-ci_assume_aws_access_key.role_arn))

- name: lifecycle-log
  type: gcs
  tags: [ "openstack" ]
  source:
    bucket: bosh-openstack-cpi-blobs
    versioned_file: lifecycle.log
    json_key: ((cloud-foundry-gcp-credentials))

- name: release-notes
  type: gcs
  source:
    bucket: bosh-openstack-cpi-blobs
    versioned_file: release-notes
    json_key: ((cloud-foundry-gcp-credentials))

- name: bosh-openstack-cpi-release
  type: git
  tags: [ "openstack" ]
  source:
    uri: git@github.com:cloudfoundry/bosh-openstack-cpi-release.git
    branch: master
    private_key: ((github_deploy_key_bosh-openstack-cpi-release.private_key))

- name: bosh-openstack-cpi-release-github-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: bosh-openstack-cpi-release
    access_token: ((github_public_repo_token))

- name: release-version-semver
  type: semver
  source:
    initial_version: "35.0.0"
    driver: git
    uri: git@github.com:cloudfoundry/bosh-openstack-cpi-release.git
    branch: release-semver
    file: VERSION
    private_key: ((github_deploy_key_bosh-openstack-cpi-release.private_key))

- name: bats
  type: git
  tags: [ "openstack" ]
  source:
    uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
    branch: master

- name: bosh-release
  type: bosh-io-release
  tags: [ "openstack" ]
  source:
    repository: cloudfoundry/bosh

- name: openstack-ubuntu-jammy-stemcell
  type: bosh-io-stemcell
  tags: [ "openstack" ]
  source:
    name: bosh-openstack-kvm-ubuntu-jammy-go_agent

- name: bosh-deployment
  type: git
  tags: [ "openstack" ]
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment.git
    branch: master

- name: openstack-cpi-release-docker-image
  type: docker-image
  check_every: never
  source:
    username: ((docker.username))
    password: ((docker.password))
    repository: boshcpi/openstack-cpi-release
- name: bosh-ruby-release-registry-image
  type: registry-image
  check_every: 168h
  source:
    repository: bosh/ruby-release
    username: ((docker.username))
    password: ((docker.password))

- name: bosh-security-scanner-registry-image
  type: registry-image
  check_every: 24h
  source:
    repository: bosh/security-scanner
    username: ((docker.username))
    password: ((docker.password))

- name: golang-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-package-golang-release.git
- name: ruby-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-package-ruby-release.git
- name: bosh-ecosystem-concourse-image
  type: registry-image
  check_every: 168h
  source:
    repository: bosh/bosh-ecosystem-concourse
    username: ((docker.username))
    password: ((docker.password))
- name: weekly
  type: time
  source:
    start: 3:00 -0700
    stop: 4:30 -0700
    days: [ Saturday ]
